name: Build and Push Docker image to ECR

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_REPOSITORY }}    # 只写仓库名，例如 foodie-server
        run: |
          set -euo pipefail
          echo "Registry: $REGISTRY"
          echo "Repository: $REPOSITORY"

          IMAGE_LATEST="$REGISTRY/$REPOSITORY:latest"
          IMAGE_SHA="$REGISTRY/$REPOSITORY:${GITHUB_SHA}"

          docker build -t "$IMAGE_LATEST" .
          docker tag "$IMAGE_LATEST" "$IMAGE_SHA"

          docker push "$IMAGE_LATEST"
          docker push "$IMAGE_SHA"

          # 可选：列出 ECR 中的镜像（失败不致命，仅日志）
          aws ecr describe-images --repository-name "$REPOSITORY" --image-ids imageTag=latest --region us-east-2 || true
          aws ecr describe-images --repository-name "$REPOSITORY" --image-ids imageTag="${GITHUB_SHA}" --region us-east-2 || true
